// Code generated by "stringer -type=Command,CRC,Measure -output=sgp30_strings.go"; DO NOT EDIT.

package sgp30

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CmdSoftReset-6]
	_ = x[CmdSoftResetMSB-0]
	_ = x[CmdSoftResetLSB-6]
	_ = x[CmdIaqInit-8195]
	_ = x[CmdIaqInitMSB-32]
	_ = x[CmdIaqInitLSB-3]
	_ = x[CmdMeasureIaq-8200]
	_ = x[CmdMeasureIaqMSB-32]
	_ = x[CmdMeasureIaqLSB-8]
	_ = x[CmdGetIaqBaseline-8213]
	_ = x[CmdGetIaqBaselineMSB-32]
	_ = x[CmdGetIaqBaselineLSB-21]
	_ = x[CmdSetIaqBaseline-8222]
	_ = x[CmdSetIaqBaselineMSB-32]
	_ = x[CmdSetIaqBaselineLSB-30]
	_ = x[CmdSetAbsoluteHumidity-8289]
	_ = x[CmdSetAbsoluteHumidityMSB-32]
	_ = x[CmdSetAbsoluteHumidityLSB-97]
	_ = x[CmdMeasureTest-8242]
	_ = x[CmdMeasureTestMSB-32]
	_ = x[CmdMeasureTestLSB-50]
	_ = x[CmdGetFeatureSet-8239]
	_ = x[CmdGetFeatureSetMSB-32]
	_ = x[CmdGetFeatureSetLSB-47]
	_ = x[CmdMeasureRaw-8272]
	_ = x[CmdMeasureRawMSB-32]
	_ = x[CmdMeasureRawLSB-80]
	_ = x[CmdGetTvocInceptiveBaseline-8371]
	_ = x[CmdGetTvocInceptiveBaselineMSB-32]
	_ = x[CmdGetTvocInceptiveBaselineLSB-179]
	_ = x[CmdSetTvocBaseline-8311]
	_ = x[CmdSetTvocBaselineMSB-32]
	_ = x[CmdSetTvocBaselineLSB-119]
	_ = x[CmdGetSerialId-13954]
	_ = x[CmdGetSerialIdMSB-54]
	_ = x[CmdGetSerialIdLSB-130]
}

const _Command_name = "CmdSoftResetMSBCmdIaqInitLSBCmdSoftResetCmdMeasureIaqLSBCmdGetIaqBaselineLSBCmdSetIaqBaselineLSBCmdIaqInitMSBCmdGetFeatureSetLSBCmdMeasureTestLSBCmdGetSerialIdMSBCmdMeasureRawLSBCmdSetAbsoluteHumidityLSBCmdSetTvocBaselineLSBCmdGetSerialIdLSBCmdGetTvocInceptiveBaselineLSBCmdIaqInitCmdMeasureIaqCmdGetIaqBaselineCmdSetIaqBaselineCmdGetFeatureSetCmdMeasureTestCmdMeasureRawCmdSetAbsoluteHumidityCmdSetTvocBaselineCmdGetTvocInceptiveBaselineCmdGetSerialId"

var _Command_map = map[Command]string{
	0:     _Command_name[0:15],
	3:     _Command_name[15:28],
	6:     _Command_name[28:40],
	8:     _Command_name[40:56],
	21:    _Command_name[56:76],
	30:    _Command_name[76:96],
	32:    _Command_name[96:109],
	47:    _Command_name[109:128],
	50:    _Command_name[128:145],
	54:    _Command_name[145:162],
	80:    _Command_name[162:178],
	97:    _Command_name[178:203],
	119:   _Command_name[203:224],
	130:   _Command_name[224:241],
	179:   _Command_name[241:271],
	8195:  _Command_name[271:281],
	8200:  _Command_name[281:294],
	8213:  _Command_name[294:311],
	8222:  _Command_name[311:328],
	8239:  _Command_name[328:344],
	8242:  _Command_name[344:358],
	8272:  _Command_name[358:371],
	8289:  _Command_name[371:393],
	8311:  _Command_name[393:411],
	8371:  _Command_name[411:438],
	13954: _Command_name[438:452],
}

func (i Command) String() string {
	if str, ok := _Command_map[i]; ok {
		return str
	}
	return "Command(" + strconv.FormatInt(int64(i), 10) + ")"
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CrcMask-49]
	_ = x[CrcBase-255]
	_ = x[CrcMsbit-128]
}

const (
	_CRC_name_0 = "CrcMask"
	_CRC_name_1 = "CrcMsbit"
	_CRC_name_2 = "CrcBase"
)

func (i CRC) String() string {
	switch {
	case i == 49:
		return _CRC_name_0
	case i == 128:
		return _CRC_name_1
	case i == 255:
		return _CRC_name_2
	default:
		return "CRC(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MeasureTest-54272]
	_ = x[FeatureSet-34]
}

const (
	_Measure_name_0 = "FeatureSet"
	_Measure_name_1 = "MeasureTest"
)

func (i Measure) String() string {
	switch {
	case i == 34:
		return _Measure_name_0
	case i == 54272:
		return _Measure_name_1
	default:
		return "Measure(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
