// Code generated by "stringer -type=Register,OpCode,SleepConfig,StandbyMode,RegulatorMode,TxRxTimeout,FallbackMode,CalibrationImageFreq,CalibrationParam,PaConfigDeviceSel,RampTime,IrqMask,Dio2Mode,TcxoVoltage,TcxoDelay,PacketType,LoRaBandwidth,LoRaCodingRate,LoRaLowDataRateOptimize,LoRaHeaderType,LoRaCrcMode,LoRaIQMode,FskPulseShape,FskBandwidth,FskPreambleDetector,FskAddressComp,FskPacketLengthMode,FskCrcType,FskWhitening,CadSymbolNum,CadExitMode,StatusMode,CommandStatus,DeviceError,FskSyncWord,RxGain,DriverStatus -output=sx126x_strings.go"; DO NOT EDIT.

package sx126x

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RegDIOxOutputEnable-1408]
	_ = x[RegDIOxInputEnable-1411]
	_ = x[RegDIOxPullUpControl-1412]
	_ = x[RegDIOxPullDownControl-1413]
	_ = x[RegFskWhiteningInitialMsb-1720]
	_ = x[RegFSkWhiteningInitialLsb-1721]
	_ = x[RegFskCrcInitialMsb-1724]
	_ = x[RegFskCrcInitialLsb-1725]
	_ = x[RegFskCrcPolyMsb-1726]
	_ = x[RegFskCrcPoluLsb-1727]
	_ = x[RegFskSyncWord0-1728]
	_ = x[RegFskSyncWord1-1729]
	_ = x[RegFskSyncWord2-1730]
	_ = x[RegFskSyncWord3-1731]
	_ = x[RegFskSyncWord4-1732]
	_ = x[RegFskSyncWord5-1733]
	_ = x[RegFskSyncWord6-1734]
	_ = x[RegFskSyncWord7-1735]
	_ = x[RegFskNodeAddress-1741]
	_ = x[RegFskBroadcastAddress-1742]
	_ = x[RegIqPolaritySetup-1846]
	_ = x[RegLoraSyncWordMsb-1856]
	_ = x[RegLoraSyncWordLsb-1857]
	_ = x[RegRandomNumberGen0-2073]
	_ = x[RegRandomNumberGen1-2074]
	_ = x[RegRandomNumberGen2-2075]
	_ = x[RegRandomNumberGen3-2076]
	_ = x[RegTxModulation-2185]
	_ = x[RegRxGain-2220]
	_ = x[RegTxClampConfig-2264]
	_ = x[RegOcpConfiguration-2279]
	_ = x[RegRtcControl-2306]
	_ = x[RegXtaTrim-2321]
	_ = x[RegXtbTrim-2322]
	_ = x[RegDIO3OutputVoltageControl-2336]
	_ = x[RegEventMask-2372]
}

const _Register_name = "RegDIOxOutputEnableRegDIOxInputEnableRegDIOxPullUpControlRegDIOxPullDownControlRegFskWhiteningInitialMsbRegFSkWhiteningInitialLsbRegFskCrcInitialMsbRegFskCrcInitialLsbRegFskCrcPolyMsbRegFskCrcPoluLsbRegFskSyncWord0RegFskSyncWord1RegFskSyncWord2RegFskSyncWord3RegFskSyncWord4RegFskSyncWord5RegFskSyncWord6RegFskSyncWord7RegFskNodeAddressRegFskBroadcastAddressRegIqPolaritySetupRegLoraSyncWordMsbRegLoraSyncWordLsbRegRandomNumberGen0RegRandomNumberGen1RegRandomNumberGen2RegRandomNumberGen3RegTxModulationRegRxGainRegTxClampConfigRegOcpConfigurationRegRtcControlRegXtaTrimRegXtbTrimRegDIO3OutputVoltageControlRegEventMask"

var _Register_map = map[Register]string{
	1408: _Register_name[0:19],
	1411: _Register_name[19:37],
	1412: _Register_name[37:57],
	1413: _Register_name[57:79],
	1720: _Register_name[79:104],
	1721: _Register_name[104:129],
	1724: _Register_name[129:148],
	1725: _Register_name[148:167],
	1726: _Register_name[167:183],
	1727: _Register_name[183:199],
	1728: _Register_name[199:214],
	1729: _Register_name[214:229],
	1730: _Register_name[229:244],
	1731: _Register_name[244:259],
	1732: _Register_name[259:274],
	1733: _Register_name[274:289],
	1734: _Register_name[289:304],
	1735: _Register_name[304:319],
	1741: _Register_name[319:336],
	1742: _Register_name[336:358],
	1846: _Register_name[358:376],
	1856: _Register_name[376:394],
	1857: _Register_name[394:412],
	2073: _Register_name[412:431],
	2074: _Register_name[431:450],
	2075: _Register_name[450:469],
	2076: _Register_name[469:488],
	2185: _Register_name[488:503],
	2220: _Register_name[503:512],
	2264: _Register_name[512:528],
	2279: _Register_name[528:547],
	2306: _Register_name[547:560],
	2321: _Register_name[560:570],
	2322: _Register_name[570:580],
	2336: _Register_name[580:607],
	2372: _Register_name[607:619],
}

func (i Register) String() string {
	if str, ok := _Register_map[i]; ok {
		return str
	}
	return "Register(" + strconv.FormatInt(int64(i), 10) + ")"
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CmdSetSleep-132]
	_ = x[CmdSetStandby-128]
	_ = x[CmdSetFs-193]
	_ = x[CmdSetTx-131]
	_ = x[CmdSetRx-130]
	_ = x[CmdSetRxDutyCycle-148]
	_ = x[CmdSetCad-197]
	_ = x[CmdSetTxContinuousWave-209]
	_ = x[CmdSetTxInfinitePreamble-210]
	_ = x[CmdSetRegulatorMode-150]
	_ = x[CmdCalibrate-137]
	_ = x[CmdCalibrateImage-152]
	_ = x[CmdSetPaConfig-149]
	_ = x[CmdSetRxTxFallbackMode-147]
	_ = x[CmdWriteRegister-13]
	_ = x[CmdReadRegister-29]
	_ = x[CmdWriteBuffer-14]
	_ = x[CmdReadBuffer-30]
	_ = x[CmdGetBufferStatus-19]
	_ = x[CmdSetDioIrqParams-8]
	_ = x[CmdGetIrqStatus-18]
	_ = x[CmdClearIrqStatus-2]
	_ = x[CmdSetDio2AsRfSwitchCtrl-157]
	_ = x[CmdSetDio3AsTcxoCtrl-151]
	_ = x[CmdSetRfFrequency-134]
	_ = x[CmdSetPacketType-138]
	_ = x[CmdGetPacketType-17]
	_ = x[CmdSetTxParams-142]
	_ = x[CmdSetModulationParams-139]
	_ = x[CmdSetPacketParams-140]
	_ = x[CmdGetStatus-192]
	_ = x[CmdGetStats-16]
	_ = x[CmdGetDeviceErrors-23]
	_ = x[CmdClearDeviceErrors-7]
	_ = x[CmdSetBufferBaseAddress-143]
	_ = x[CmdStopOnPreamble-159]
	_ = x[CmdSetCadParams-136]
	_ = x[CmdSetSymbNumTimeout-160]
	_ = x[CmdGetPacketStatus-20]
	_ = x[CmdGetPacketRssi-21]
	_ = x[CmdResetStats-0]
	_ = x[CmdResetErrors-7]
}

const _OpCode_name = "CmdResetStatsCmdClearIrqStatusCmdClearDeviceErrorsCmdSetDioIrqParamsCmdWriteRegisterCmdWriteBufferCmdGetStatsCmdGetPacketTypeCmdGetIrqStatusCmdGetBufferStatusCmdGetPacketStatusCmdGetPacketRssiCmdGetDeviceErrorsCmdReadRegisterCmdReadBufferCmdSetStandbyCmdSetRxCmdSetTxCmdSetSleepCmdSetRfFrequencyCmdSetCadParamsCmdCalibrateCmdSetPacketTypeCmdSetModulationParamsCmdSetPacketParamsCmdSetTxParamsCmdSetBufferBaseAddressCmdSetRxTxFallbackModeCmdSetRxDutyCycleCmdSetPaConfigCmdSetRegulatorModeCmdSetDio3AsTcxoCtrlCmdCalibrateImageCmdSetDio2AsRfSwitchCtrlCmdStopOnPreambleCmdSetSymbNumTimeoutCmdGetStatusCmdSetFsCmdSetCadCmdSetTxContinuousWaveCmdSetTxInfinitePreamble"

var _OpCode_map = map[OpCode]string{
	0:   _OpCode_name[0:13],
	2:   _OpCode_name[13:30],
	7:   _OpCode_name[30:50],
	8:   _OpCode_name[50:68],
	13:  _OpCode_name[68:84],
	14:  _OpCode_name[84:98],
	16:  _OpCode_name[98:109],
	17:  _OpCode_name[109:125],
	18:  _OpCode_name[125:140],
	19:  _OpCode_name[140:158],
	20:  _OpCode_name[158:176],
	21:  _OpCode_name[176:192],
	23:  _OpCode_name[192:210],
	29:  _OpCode_name[210:225],
	30:  _OpCode_name[225:238],
	128: _OpCode_name[238:251],
	130: _OpCode_name[251:259],
	131: _OpCode_name[259:267],
	132: _OpCode_name[267:278],
	134: _OpCode_name[278:295],
	136: _OpCode_name[295:310],
	137: _OpCode_name[310:322],
	138: _OpCode_name[322:338],
	139: _OpCode_name[338:360],
	140: _OpCode_name[360:378],
	142: _OpCode_name[378:392],
	143: _OpCode_name[392:415],
	147: _OpCode_name[415:437],
	148: _OpCode_name[437:454],
	149: _OpCode_name[454:468],
	150: _OpCode_name[468:487],
	151: _OpCode_name[487:507],
	152: _OpCode_name[507:524],
	157: _OpCode_name[524:548],
	159: _OpCode_name[548:565],
	160: _OpCode_name[565:585],
	192: _OpCode_name[585:597],
	193: _OpCode_name[597:605],
	197: _OpCode_name[605:614],
	209: _OpCode_name[614:636],
	210: _OpCode_name[636:660],
}

func (i OpCode) String() string {
	if str, ok := _OpCode_map[i]; ok {
		return str
	}
	return "OpCode(" + strconv.FormatInt(int64(i), 10) + ")"
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SleepColdStart-0]
	_ = x[SleepWarmStart-4]
	_ = x[SleepColdStartRtc-1]
	_ = x[SleepWarmStartRtc-5]
}

const (
	_SleepConfig_name_0 = "SleepColdStartSleepColdStartRtc"
	_SleepConfig_name_1 = "SleepWarmStartSleepWarmStartRtc"
)

var (
	_SleepConfig_index_0 = [...]uint8{0, 14, 31}
	_SleepConfig_index_1 = [...]uint8{0, 14, 31}
)

func (i SleepConfig) String() string {
	switch {
	case i <= 1:
		return _SleepConfig_name_0[_SleepConfig_index_0[i]:_SleepConfig_index_0[i+1]]
	case 4 <= i && i <= 5:
		i -= 4
		return _SleepConfig_name_1[_SleepConfig_index_1[i]:_SleepConfig_index_1[i+1]]
	default:
		return "SleepConfig(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StandbyRc-0]
	_ = x[StandbyXosc-1]
}

const _StandbyMode_name = "StandbyRcStandbyXosc"

var _StandbyMode_index = [...]uint8{0, 9, 20}

func (i StandbyMode) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_StandbyMode_index)-1 {
		return "StandbyMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StandbyMode_name[_StandbyMode_index[idx]:_StandbyMode_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RegulatorLdo-0]
	_ = x[RegulatorDcDc-1]
}

const _RegulatorMode_name = "RegulatorLdoRegulatorDcDc"

var _RegulatorMode_index = [...]uint8{0, 12, 25}

func (i RegulatorMode) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_RegulatorMode_index)-1 {
		return "RegulatorMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RegulatorMode_name[_RegulatorMode_index[idx]:_RegulatorMode_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TxSingle-0]
	_ = x[RxSingle-0]
	_ = x[RxContinuous-16777215]
}

const (
	_TxRxTimeout_name_0 = "TxSingle"
	_TxRxTimeout_name_1 = "RxContinuous"
)

func (i TxRxTimeout) String() string {
	switch {
	case i == 0:
		return _TxRxTimeout_name_0
	case i == 16777215:
		return _TxRxTimeout_name_1
	default:
		return "TxRxTimeout(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FallbackFs-64]
	_ = x[FallbackStdbyXosc-48]
	_ = x[FallbackStdbyRc-32]
}

const (
	_FallbackMode_name_0 = "FallbackStdbyRc"
	_FallbackMode_name_1 = "FallbackStdbyXosc"
	_FallbackMode_name_2 = "FallbackFs"
)

func (i FallbackMode) String() string {
	switch {
	case i == 32:
		return _FallbackMode_name_0
	case i == 48:
		return _FallbackMode_name_1
	case i == 64:
		return _FallbackMode_name_2
	default:
		return "FallbackMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CalImg430-107]
	_ = x[CalImg440-111]
	_ = x[CalImg470-117]
	_ = x[CalImg510-129]
	_ = x[CalImg779-193]
	_ = x[CalImg787-197]
	_ = x[CalImg863-215]
	_ = x[CalImg870-219]
	_ = x[CalImg902-225]
	_ = x[CalImg928-233]
}

const (
	_CalibrationImageFreq_name_0 = "CalImg430"
	_CalibrationImageFreq_name_1 = "CalImg440"
	_CalibrationImageFreq_name_2 = "CalImg470"
	_CalibrationImageFreq_name_3 = "CalImg510"
	_CalibrationImageFreq_name_4 = "CalImg779"
	_CalibrationImageFreq_name_5 = "CalImg787"
	_CalibrationImageFreq_name_6 = "CalImg863"
	_CalibrationImageFreq_name_7 = "CalImg870"
	_CalibrationImageFreq_name_8 = "CalImg902"
	_CalibrationImageFreq_name_9 = "CalImg928"
)

func (i CalibrationImageFreq) String() string {
	switch {
	case i == 107:
		return _CalibrationImageFreq_name_0
	case i == 111:
		return _CalibrationImageFreq_name_1
	case i == 117:
		return _CalibrationImageFreq_name_2
	case i == 129:
		return _CalibrationImageFreq_name_3
	case i == 193:
		return _CalibrationImageFreq_name_4
	case i == 197:
		return _CalibrationImageFreq_name_5
	case i == 215:
		return _CalibrationImageFreq_name_6
	case i == 219:
		return _CalibrationImageFreq_name_7
	case i == 225:
		return _CalibrationImageFreq_name_8
	case i == 233:
		return _CalibrationImageFreq_name_9
	default:
		return "CalibrationImageFreq(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CalibNone-0]
	_ = x[CalibRC64k-1]
	_ = x[CalibRC13M-2]
	_ = x[CalibPLL-4]
	_ = x[CalibADCPulse-8]
	_ = x[CalibADCBulkN-16]
	_ = x[CalibADCBulkP-32]
	_ = x[CalibAll-63]
}

const (
	_CalibrationParam_name_0 = "CalibNoneCalibRC64kCalibRC13M"
	_CalibrationParam_name_1 = "CalibPLL"
	_CalibrationParam_name_2 = "CalibADCPulse"
	_CalibrationParam_name_3 = "CalibADCBulkN"
	_CalibrationParam_name_4 = "CalibADCBulkP"
	_CalibrationParam_name_5 = "CalibAll"
)

var (
	_CalibrationParam_index_0 = [...]uint8{0, 9, 19, 29}
)

func (i CalibrationParam) String() string {
	switch {
	case i <= 2:
		return _CalibrationParam_name_0[_CalibrationParam_index_0[i]:_CalibrationParam_index_0[i+1]]
	case i == 4:
		return _CalibrationParam_name_1
	case i == 8:
		return _CalibrationParam_name_2
	case i == 16:
		return _CalibrationParam_name_3
	case i == 32:
		return _CalibrationParam_name_4
	case i == 63:
		return _CalibrationParam_name_5
	default:
		return "CalibrationParam(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TxPowerSX1261-1]
	_ = x[TxPowerSX1262-0]
}

const _PaConfigDeviceSel_name = "TxPowerSX1262TxPowerSX1261"

var _PaConfigDeviceSel_index = [...]uint8{0, 13, 26}

func (i PaConfigDeviceSel) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_PaConfigDeviceSel_index)-1 {
		return "PaConfigDeviceSel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PaConfigDeviceSel_name[_PaConfigDeviceSel_index[idx]:_PaConfigDeviceSel_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PaRamp10u-0]
	_ = x[PaRamp20u-1]
	_ = x[PaRamp40u-2]
	_ = x[PaRamp80u-3]
	_ = x[PaRamp200u-4]
	_ = x[PaRamp800u-5]
	_ = x[PaRamp1700u-6]
	_ = x[PaRamp3400u-7]
}

const _RampTime_name = "PaRamp10uPaRamp20uPaRamp40uPaRamp80uPaRamp200uPaRamp800uPaRamp1700uPaRamp3400u"

var _RampTime_index = [...]uint8{0, 9, 18, 27, 36, 46, 56, 67, 78}

func (i RampTime) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_RampTime_index)-1 {
		return "RampTime(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RampTime_name[_RampTime_index[idx]:_RampTime_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[IrqTxDone-1]
	_ = x[IrqRxDone-2]
	_ = x[IrqPreambleDetected-4]
	_ = x[IrqSyncWordValid-8]
	_ = x[IrqHeaderValid-16]
	_ = x[IrqHeaderErr-32]
	_ = x[IrqCrcErr-64]
	_ = x[IrqCadDone-128]
	_ = x[IrqCadDetected-256]
	_ = x[IrqTimeout-512]
	_ = x[IrqAll-1023]
	_ = x[IrqNone-0]
}

const (
	_IrqMask_name_0 = "IrqNoneIrqTxDoneIrqRxDone"
	_IrqMask_name_1 = "IrqPreambleDetected"
	_IrqMask_name_2 = "IrqSyncWordValid"
	_IrqMask_name_3 = "IrqHeaderValid"
	_IrqMask_name_4 = "IrqHeaderErr"
	_IrqMask_name_5 = "IrqCrcErr"
	_IrqMask_name_6 = "IrqCadDone"
	_IrqMask_name_7 = "IrqCadDetected"
	_IrqMask_name_8 = "IrqTimeout"
	_IrqMask_name_9 = "IrqAll"
)

var (
	_IrqMask_index_0 = [...]uint8{0, 7, 16, 25}
)

func (i IrqMask) String() string {
	switch {
	case i <= 2:
		return _IrqMask_name_0[_IrqMask_index_0[i]:_IrqMask_index_0[i+1]]
	case i == 4:
		return _IrqMask_name_1
	case i == 8:
		return _IrqMask_name_2
	case i == 16:
		return _IrqMask_name_3
	case i == 32:
		return _IrqMask_name_4
	case i == 64:
		return _IrqMask_name_5
	case i == 128:
		return _IrqMask_name_6
	case i == 256:
		return _IrqMask_name_7
	case i == 512:
		return _IrqMask_name_8
	case i == 1023:
		return _IrqMask_name_9
	default:
		return "IrqMask(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Dio2AsIrq-0]
	_ = x[Dio2AsRfSwitch-1]
}

const _Dio2Mode_name = "Dio2AsIrqDio2AsRfSwitch"

var _Dio2Mode_index = [...]uint8{0, 9, 23}

func (i Dio2Mode) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Dio2Mode_index)-1 {
		return "Dio2Mode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Dio2Mode_name[_Dio2Mode_index[idx]:_Dio2Mode_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Dio3Output1_6-0]
	_ = x[Dio3Output1_7-1]
	_ = x[Dio3Output1_8-2]
	_ = x[Dio3Output2_2-3]
	_ = x[Dio3Output2_4-4]
	_ = x[Dio3Output2_7-5]
	_ = x[Dio3Output3_0-6]
	_ = x[Dio3Output3_3-7]
}

const _TcxoVoltage_name = "Dio3Output1_6Dio3Output1_7Dio3Output1_8Dio3Output2_2Dio3Output2_4Dio3Output2_7Dio3Output3_0Dio3Output3_3"

var _TcxoVoltage_index = [...]uint8{0, 13, 26, 39, 52, 65, 78, 91, 104}

func (i TcxoVoltage) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TcxoVoltage_index)-1 {
		return "TcxoVoltage(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TcxoVoltage_name[_TcxoVoltage_index[idx]:_TcxoVoltage_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TcxoDelay2_5-320]
	_ = x[TcxoDelay5-640]
	_ = x[TcxoDelay10-1376]
}

const (
	_TcxoDelay_name_0 = "TcxoDelay2_5"
	_TcxoDelay_name_1 = "TcxoDelay5"
	_TcxoDelay_name_2 = "TcxoDelay10"
)

func (i TcxoDelay) String() string {
	switch {
	case i == 320:
		return _TcxoDelay_name_0
	case i == 640:
		return _TcxoDelay_name_1
	case i == 1376:
		return _TcxoDelay_name_2
	default:
		return "TcxoDelay(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PacketTypeGFSK-0]
	_ = x[PacketTypeLoRa-1]
	_ = x[PacketTypeGFSKStatic-0]
	_ = x[PacketTypeGFSKVariable-1]
}

const _PacketType_name = "PacketTypeGFSKPacketTypeLoRa"

var _PacketType_index = [...]uint8{0, 14, 28}

func (i PacketType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_PacketType_index)-1 {
		return "PacketType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PacketType_name[_PacketType_index[idx]:_PacketType_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LoRaBW_7_8-0]
	_ = x[LoRaBW_10_4-8]
	_ = x[LoRaBW_15_6-1]
	_ = x[LoRaBW_20_8-9]
	_ = x[LoRaBW_31_25-2]
	_ = x[LoRaBW_41_7-10]
	_ = x[LoRaBW_62_5-3]
	_ = x[LoRaBW_125-4]
	_ = x[LoRaBW_250-5]
	_ = x[LoRaBW_500-6]
}

const (
	_LoRaBandwidth_name_0 = "LoRaBW_7_8LoRaBW_15_6LoRaBW_31_25LoRaBW_62_5LoRaBW_125LoRaBW_250LoRaBW_500"
	_LoRaBandwidth_name_1 = "LoRaBW_10_4LoRaBW_20_8LoRaBW_41_7"
)

var (
	_LoRaBandwidth_index_0 = [...]uint8{0, 10, 21, 33, 44, 54, 64, 74}
	_LoRaBandwidth_index_1 = [...]uint8{0, 11, 22, 33}
)

func (i LoRaBandwidth) String() string {
	switch {
	case i <= 6:
		return _LoRaBandwidth_name_0[_LoRaBandwidth_index_0[i]:_LoRaBandwidth_index_0[i+1]]
	case 8 <= i && i <= 10:
		i -= 8
		return _LoRaBandwidth_name_1[_LoRaBandwidth_index_1[i]:_LoRaBandwidth_index_1[i+1]]
	default:
		return "LoRaBandwidth(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LoRaCR_4_5-1]
	_ = x[LoRaCR_4_6-2]
	_ = x[LoRaCR_4_7-3]
	_ = x[LoRaCR_4_8-4]
}

const _LoRaCodingRate_name = "LoRaCR_4_5LoRaCR_4_6LoRaCR_4_7LoRaCR_4_8"

var _LoRaCodingRate_index = [...]uint8{0, 10, 20, 30, 40}

func (i LoRaCodingRate) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_LoRaCodingRate_index)-1 {
		return "LoRaCodingRate(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LoRaCodingRate_name[_LoRaCodingRate_index[idx]:_LoRaCodingRate_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LDRO_OFF-0]
	_ = x[LDRO_ON-1]
}

const _LoRaLowDataRateOptimize_name = "LDRO_OFFLDRO_ON"

var _LoRaLowDataRateOptimize_index = [...]uint8{0, 8, 15}

func (i LoRaLowDataRateOptimize) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_LoRaLowDataRateOptimize_index)-1 {
		return "LoRaLowDataRateOptimize(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LoRaLowDataRateOptimize_name[_LoRaLowDataRateOptimize_index[idx]:_LoRaLowDataRateOptimize_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HeaderExplicit-0]
	_ = x[HeaderImplicit-1]
}

const _LoRaHeaderType_name = "HeaderExplicitHeaderImplicit"

var _LoRaHeaderType_index = [...]uint8{0, 14, 28}

func (i LoRaHeaderType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_LoRaHeaderType_index)-1 {
		return "LoRaHeaderType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LoRaHeaderType_name[_LoRaHeaderType_index[idx]:_LoRaHeaderType_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CrcOff-0]
	_ = x[CrcOn-1]
}

const _LoRaCrcMode_name = "CrcOffCrcOn"

var _LoRaCrcMode_index = [...]uint8{0, 6, 11}

func (i LoRaCrcMode) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_LoRaCrcMode_index)-1 {
		return "LoRaCrcMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LoRaCrcMode_name[_LoRaCrcMode_index[idx]:_LoRaCrcMode_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[IqStandard-0]
	_ = x[IqInverted-1]
}

const _LoRaIQMode_name = "IqStandardIqInverted"

var _LoRaIQMode_index = [...]uint8{0, 10, 20}

func (i LoRaIQMode) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_LoRaIQMode_index)-1 {
		return "LoRaIQMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LoRaIQMode_name[_LoRaIQMode_index[idx]:_LoRaIQMode_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PulseNoFilter-0]
	_ = x[PulseGaussianBt0_3-8]
	_ = x[PulseGaussianBt0_5-9]
	_ = x[PulseGaussianBt0_7-10]
	_ = x[PulseGaussianBt1-11]
}

const (
	_FskPulseShape_name_0 = "PulseNoFilter"
	_FskPulseShape_name_1 = "PulseGaussianBt0_3PulseGaussianBt0_5PulseGaussianBt0_7PulseGaussianBt1"
)

var (
	_FskPulseShape_index_1 = [...]uint8{0, 18, 36, 54, 70}
)

func (i FskPulseShape) String() string {
	switch {
	case i == 0:
		return _FskPulseShape_name_0
	case 8 <= i && i <= 11:
		i -= 8
		return _FskPulseShape_name_1[_FskPulseShape_index_1[i]:_FskPulseShape_index_1[i+1]]
	default:
		return "FskPulseShape(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FskBW_4800-31]
	_ = x[FskBW_5800-23]
	_ = x[FskBW_7300-15]
	_ = x[FskBW_9700-30]
	_ = x[FskBW_11700-22]
	_ = x[FskBW_14600-14]
	_ = x[FskBW_19500-29]
	_ = x[FskBW_23400-21]
	_ = x[FskBW_29300-13]
	_ = x[FskBW_39000-28]
	_ = x[FskBW_46900-20]
	_ = x[FskBW_58600-12]
	_ = x[FskBW_78200-27]
	_ = x[FskBW_93800-19]
	_ = x[FskBW_117300-11]
	_ = x[FskBW_156200-26]
	_ = x[FskBW_187200-18]
	_ = x[FskBW_234300-10]
	_ = x[FskBW_312000-25]
	_ = x[FskBW_373600-17]
	_ = x[FskBW_467000-9]
}

const (
	_FskBandwidth_name_0 = "FskBW_467000FskBW_234300FskBW_117300FskBW_58600FskBW_29300FskBW_14600FskBW_7300"
	_FskBandwidth_name_1 = "FskBW_373600FskBW_187200FskBW_93800FskBW_46900FskBW_23400FskBW_11700FskBW_5800"
	_FskBandwidth_name_2 = "FskBW_312000FskBW_156200FskBW_78200FskBW_39000FskBW_19500FskBW_9700FskBW_4800"
)

var (
	_FskBandwidth_index_0 = [...]uint8{0, 12, 24, 36, 47, 58, 69, 79}
	_FskBandwidth_index_1 = [...]uint8{0, 12, 24, 35, 46, 57, 68, 78}
	_FskBandwidth_index_2 = [...]uint8{0, 12, 24, 35, 46, 57, 67, 77}
)

func (i FskBandwidth) String() string {
	switch {
	case 9 <= i && i <= 15:
		i -= 9
		return _FskBandwidth_name_0[_FskBandwidth_index_0[i]:_FskBandwidth_index_0[i+1]]
	case 17 <= i && i <= 23:
		i -= 17
		return _FskBandwidth_name_1[_FskBandwidth_index_1[i]:_FskBandwidth_index_1[i+1]]
	case 25 <= i && i <= 31:
		i -= 25
		return _FskBandwidth_name_2[_FskBandwidth_index_2[i]:_FskBandwidth_index_2[i+1]]
	default:
		return "FskBandwidth(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PreambleDetLenOff-0]
	_ = x[PreambleDetLen8-4]
	_ = x[PreambleDetLen16-5]
	_ = x[PreambleDetLen24-6]
	_ = x[PreambleDetLen32-7]
}

const (
	_FskPreambleDetector_name_0 = "PreambleDetLenOff"
	_FskPreambleDetector_name_1 = "PreambleDetLen8PreambleDetLen16PreambleDetLen24PreambleDetLen32"
)

var (
	_FskPreambleDetector_index_1 = [...]uint8{0, 15, 31, 47, 63}
)

func (i FskPreambleDetector) String() string {
	switch {
	case i == 0:
		return _FskPreambleDetector_name_0
	case 4 <= i && i <= 7:
		i -= 4
		return _FskPreambleDetector_name_1[_FskPreambleDetector_index_1[i]:_FskPreambleDetector_index_1[i+1]]
	default:
		return "FskPreambleDetector(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AddrCompOff-0]
	_ = x[AddrCompNode-1]
	_ = x[AddrCompAll-2]
}

const _FskAddressComp_name = "AddrCompOffAddrCompNodeAddrCompAll"

var _FskAddressComp_index = [...]uint8{0, 11, 23, 34}

func (i FskAddressComp) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_FskAddressComp_index)-1 {
		return "FskAddressComp(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FskAddressComp_name[_FskAddressComp_index[idx]:_FskAddressComp_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PacketKnown-0]
	_ = x[PacketVariable-1]
}

const _FskPacketLengthMode_name = "PacketKnownPacketVariable"

var _FskPacketLengthMode_index = [...]uint8{0, 11, 25}

func (i FskPacketLengthMode) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_FskPacketLengthMode_index)-1 {
		return "FskPacketLengthMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FskPacketLengthMode_name[_FskPacketLengthMode_index[idx]:_FskPacketLengthMode_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CRC0-1]
	_ = x[CRC1-0]
	_ = x[CRC2-2]
	_ = x[CRC1Inv-4]
	_ = x[CRC2Inv-6]
}

const (
	_FskCrcType_name_0 = "CRC1CRC0CRC2"
	_FskCrcType_name_1 = "CRC1Inv"
	_FskCrcType_name_2 = "CRC2Inv"
)

var (
	_FskCrcType_index_0 = [...]uint8{0, 4, 8, 12}
)

func (i FskCrcType) String() string {
	switch {
	case i <= 2:
		return _FskCrcType_name_0[_FskCrcType_index_0[i]:_FskCrcType_index_0[i+1]]
	case i == 4:
		return _FskCrcType_name_1
	case i == 6:
		return _FskCrcType_name_2
	default:
		return "FskCrcType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[WhiteningOff-0]
	_ = x[WhiteningOn-1]
}

const _FskWhitening_name = "WhiteningOffWhiteningOn"

var _FskWhitening_index = [...]uint8{0, 12, 23}

func (i FskWhitening) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_FskWhitening_index)-1 {
		return "FskWhitening(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FskWhitening_name[_FskWhitening_index[idx]:_FskWhitening_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CadOn1Symb-0]
	_ = x[CadOn2Symb-1]
	_ = x[CadOn4Symb-2]
	_ = x[CadOn8Symb-3]
	_ = x[CadOn16Symb-4]
}

const _CadSymbolNum_name = "CadOn1SymbCadOn2SymbCadOn4SymbCadOn8SymbCadOn16Symb"

var _CadSymbolNum_index = [...]uint8{0, 10, 20, 30, 40, 51}

func (i CadSymbolNum) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_CadSymbolNum_index)-1 {
		return "CadSymbolNum(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CadSymbolNum_name[_CadSymbolNum_index[idx]:_CadSymbolNum_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CadExitStdby-0]
	_ = x[CadExitRx-1]
}

const _CadExitMode_name = "CadExitStdbyCadExitRx"

var _CadExitMode_index = [...]uint8{0, 12, 21}

func (i CadExitMode) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_CadExitMode_index)-1 {
		return "CadExitMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CadExitMode_name[_CadExitMode_index[idx]:_CadExitMode_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StatusModeStdbyRc-2]
	_ = x[StatusModeStdbyXosc-3]
	_ = x[StatusModeFs-4]
	_ = x[StatusModeRx-5]
	_ = x[StatusModeTx-6]
}

const _StatusMode_name = "StatusModeStdbyRcStatusModeStdbyXoscStatusModeFsStatusModeRxStatusModeTx"

var _StatusMode_index = [...]uint8{0, 17, 36, 48, 60, 72}

func (i StatusMode) String() string {
	idx := int(i) - 2
	if i < 2 || idx >= len(_StatusMode_index)-1 {
		return "StatusMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StatusMode_name[_StatusMode_index[idx]:_StatusMode_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StatusDataAvailable-2]
	_ = x[StatusCmdTimeout-3]
	_ = x[StatusCmdProcessingError-4]
	_ = x[StatusCmdExecuteError-5]
	_ = x[StatusCmdTxDone-6]
}

const _CommandStatus_name = "StatusDataAvailableStatusCmdTimeoutStatusCmdProcessingErrorStatusCmdExecuteErrorStatusCmdTxDone"

var _CommandStatus_index = [...]uint8{0, 19, 35, 59, 80, 95}

func (i CommandStatus) String() string {
	idx := int(i) - 2
	if i < 2 || idx >= len(_CommandStatus_index)-1 {
		return "CommandStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CommandStatus_name[_CommandStatus_index[idx]:_CommandStatus_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrRC64KCalib-1]
	_ = x[ErrRC13MCalib-2]
	_ = x[ErrPllCalib-4]
	_ = x[ErrAdcCalib-8]
	_ = x[ErrImgCalib-16]
	_ = x[ErrXoscStart-32]
	_ = x[ErrPllLock-64]
	_ = x[ErrPaRamp-256]
}

const (
	_DeviceError_name_0 = "ErrRC64KCalibErrRC13MCalib"
	_DeviceError_name_1 = "ErrPllCalib"
	_DeviceError_name_2 = "ErrAdcCalib"
	_DeviceError_name_3 = "ErrImgCalib"
	_DeviceError_name_4 = "ErrXoscStart"
	_DeviceError_name_5 = "ErrPllLock"
	_DeviceError_name_6 = "ErrPaRamp"
)

var (
	_DeviceError_index_0 = [...]uint8{0, 13, 26}
)

func (i DeviceError) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _DeviceError_name_0[_DeviceError_index_0[i]:_DeviceError_index_0[i+1]]
	case i == 4:
		return _DeviceError_name_1
	case i == 8:
		return _DeviceError_name_2
	case i == 16:
		return _DeviceError_name_3
	case i == 32:
		return _DeviceError_name_4
	case i == 64:
		return _DeviceError_name_5
	case i == 256:
		return _DeviceError_name_6
	default:
		return "DeviceError(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FskSyncWordLength0-0]
	_ = x[FskSyncWordLength1-8]
	_ = x[FskSyncWordLength2-16]
	_ = x[FskSyncWordLength3-24]
	_ = x[FskSyncWordLength4-32]
	_ = x[FskSyncWordLength5-40]
	_ = x[FskSyncWordLength6-48]
	_ = x[FskSyncWordLength7-56]
	_ = x[FskSyncWordLength8-64]
}

const (
	_FskSyncWord_name_0 = "FskSyncWordLength0"
	_FskSyncWord_name_1 = "FskSyncWordLength1"
	_FskSyncWord_name_2 = "FskSyncWordLength2"
	_FskSyncWord_name_3 = "FskSyncWordLength3"
	_FskSyncWord_name_4 = "FskSyncWordLength4"
	_FskSyncWord_name_5 = "FskSyncWordLength5"
	_FskSyncWord_name_6 = "FskSyncWordLength6"
	_FskSyncWord_name_7 = "FskSyncWordLength7"
	_FskSyncWord_name_8 = "FskSyncWordLength8"
)

func (i FskSyncWord) String() string {
	switch {
	case i == 0:
		return _FskSyncWord_name_0
	case i == 8:
		return _FskSyncWord_name_1
	case i == 16:
		return _FskSyncWord_name_2
	case i == 24:
		return _FskSyncWord_name_3
	case i == 32:
		return _FskSyncWord_name_4
	case i == 40:
		return _FskSyncWord_name_5
	case i == 48:
		return _FskSyncWord_name_6
	case i == 56:
		return _FskSyncWord_name_7
	case i == 64:
		return _FskSyncWord_name_8
	default:
		return "FskSyncWord(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RxGainPowerSaving-0]
	_ = x[RxGainBoosted-1]
}

const _RxGain_name = "RxGainPowerSavingRxGainBoosted"

var _RxGain_index = [...]uint8{0, 17, 30}

func (i RxGain) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_RxGain_index)-1 {
		return "RxGain(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RxGain_name[_RxGain_index[idx]:_RxGain_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StatusDefault-0]
	_ = x[StatusTxWait-1]
	_ = x[StatusTxTimeout-2]
	_ = x[StatusTxDone-3]
	_ = x[StatusRxWait-4]
	_ = x[StatusRxContinuous-5]
	_ = x[StatusRxTimeout-6]
	_ = x[StatusRxDone-7]
	_ = x[StatusHeaderErr-8]
	_ = x[StatusCrcErr-9]
	_ = x[StatusCadWait-10]
	_ = x[StatusCadDetected-11]
	_ = x[StatusCadDone-12]
}

const _DriverStatus_name = "StatusDefaultStatusTxWaitStatusTxTimeoutStatusTxDoneStatusRxWaitStatusRxContinuousStatusRxTimeoutStatusRxDoneStatusHeaderErrStatusCrcErrStatusCadWaitStatusCadDetectedStatusCadDone"

var _DriverStatus_index = [...]uint8{0, 13, 25, 40, 52, 64, 82, 97, 109, 124, 136, 149, 166, 179}

func (i DriverStatus) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_DriverStatus_index)-1 {
		return "DriverStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DriverStatus_name[_DriverStatus_index[idx]:_DriverStatus_index[idx+1]]
}
